# Generated by Django 4.2 on 2024-05-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
